### PR TITLE
Moved the project from using groovy to using kotlin

### PR DESCRIPTION
**Pull request by krolik-exe**
+ Moved the project from using groovy to use kotlin

+ Updated gradle to 6.8.3

+ I forgot to mention in the last pr that from the gradle update from 3.3 to 6.8.2 , all version of java are supported now from 1.8 to latest , maybe some earlier versions are working too but i'm not sure , because i didn't test version earlier than 1.8

+ The build time is very similiar to earlier , with gradle 6.8.2 without kotlin , and i can't say the difference in time because one time it takes 1s and other time 3s

+ Added a runnable .jar program ( Check out #7 and this [commit](https://github.com/MiniDigger/spigot-resolver/pull/7/commits/44e951f45a028eea22df14f7da978564dbef27c5) for more info about using it)

### CODE REVIEW

**Comment by MiniDigger** [comment]
> I also removed the sourceCompatibility from build.gradle ( now build.gradle.kts ) because it wasn't needed

preeeettty sure that without that, intellij will default to java 8

**Comment by krolik-exe** [comment]
I can add that back if it's needed to be there

**Comment by krolik-exe** [comment]
Should be ok now

**Comment by krolik-exe** [comment]
I don't know how to update it to 16 and up . so i just leave there the existing links , and change some of them to be accurate

**Comment by krolik-exe** [comment]
How to run this program is gonna be explained in the readme update pr

**Comment by krolik-exe** [comment]
to clear out i only have done some changes regarding only the links , to spigotresolver.java file, and the revert 1 commit was for my non-sense doing about trying to modify it for no reason

**Comment by MiniDigger** [comment]
thanks

**Pull request merged**
